services:
  web:
    build: ./public
    image: php:apache
    volumes:
      - ./:/var/www/html
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - mysql_db
    env_file:
      - .env

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "${DBMS_PORT}:80"
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
    depends_on:
      - mysql_db
volumes:
  mysql-data: